# Generated by Django 4.2.2 on 2023-07-07 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0002_alter_empresa_ruc_alter_empresa_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
