# Generated by Django 4.2.2 on 2023-07-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0004_alter_empresa_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.PositiveIntegerField(),
        ),
    ]
