# Generated by Django 4.2.2 on 2023-07-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0005_alter_empresa_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.BigIntegerField(),
        ),
    ]
